app:
  name: Instacart Basket Analysis Prod

spark:
  app_name: Instacart Basket Analysis Prod
  master : local[*]

paths:
  raw: data/raw
  bronze: data/bronze
  silver: data/silver
  gold: data/gold